import { Routes } from '@angular/router';
import { Home } from './pages/home/home';
import { Characters } from './pages/characters/characters';
import { CharacterDetail } from './pages/character-detail/character-detail';
import { Kameos } from './pages/kameos/kameos';
import { KameoDetail } from './pages/kameo-detail/kameo-detail';
import { TierMaker } from './pages/tier-maker/tier-maker';
import { Guides } from './pages/guides/guides';
import { GuideTheMatch } from './pages/guides/the-match/the-match';
import { About } from './pages/about/about';
import { Contact } from './pages/contact/contact';
import { Credits } from './pages/credits/credits';
import { TermsOfService } from './pages/terms/terms';
import { Updates } from './pages/updates/updates';
import { Teams } from './pages/teams/teams';
import { Gameplay } from './pages/gameplay/gameplay';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'characters', component: Characters },
  { path: 'character/:name', component: CharacterDetail },
  { path: 'kameos', component: Kameos },
  { path: 'kameos/:slug', component: KameoDetail },
  { path: 'tier-maker', component: TierMaker },
  { path: 'guides', component: Guides },
  { path: 'guides/the-match', component: GuideTheMatch },
  { path: 'teams', component: Teams },
  { path: 'gameplay', component: Gameplay },
  { path: 'about', component: About },
  { path: 'contact', component: Contact },
  { path: 'credits', component: Credits },
  { path: 'terms-of-service', component: TermsOfService },
  { path: 'updates', component: Updates },
  { path: '**', redirectTo: '' }
];
